### ISSUE TITLE
Deploy works, but cannot find run-cmd message is bb logs

### ISSUE THREAD

**Issue by mintymac** [jacobobryant/eelchat#4]
@jacobobryant Thank you so much for this lib.  works great, I just have this issue when following along in the tutorial.  I very well could have missed something:

When running ```bb logs```

---

an 17 05:05:39 nspin sh[956]: ----- Error --------------------------------------------------------------------
Jan 17 05:05:39 nspin sh[956]: Type:     java.lang.Exception
Jan 17 05:05:39 nspin sh[956]: Message:  File does not exist: run-cmd

---

**Comment by jacobobryant** [comment]
That error message makes it look like the `bb deploy` command didn't work--did you notice any errors when you ran `bb deploy`?

When the app starts up on the server, [it runs `bb run-cmd`](https://github.com/jacobobryant/biff/blob/821182173945d40cde59cbd1784fc32bb5b0d4e0/example/server-setup.sh#L60) first, and then executes the result of that as a separate command. e.g. if you run `bb run-cmd` locally, you should see something like this:

```shell
$ bb run-cmd
eval mkdir -p target/resources ; . ./secrets.env ; clj '-J-XX:-OmitStackTraceInFastThrow' '-M' '-m' 'com.example' '--port' '7888' '--middleware' '[cider.nrepl/cider-middleware,refactor-nrepl.middleware/wrap-refactor]'
```

And similarly, if you ssh into your server as the `app` user (`ssh app@example.com`) and then run `bb run-cmd` you should see the same thing.

However if the first deploy didn't work, then the `bb.edn` file won't be on your server, so when you run `bb run-cmd`, babashka won't know there's supposed to be a `run-cmd` task. So it instead looks for a file called `run-cmd` to execute, and that file doesn't exist, hence the error you're getting.

If `bb deploy` does appear to work, then running `ssh app@example.com ls` would be a good next step, to verify what files have ended up on the server.

**Comment by mintymac** [comment]
Thank you for the quick response.  I think I isolated the issue to the post-receive hook, as the initial branch was set to main and not master ( git so there was no code in /home/app 

/home/app/repo.git/hooks# more post-receive
#!/usr/bin/env bash
git --work-tree=/home/app --git-dir=/home/app/repo.git checkout -f
cd /home/app
bb post-receive

I fixed it by running 
`git --work-tree=/home/app --git-dir=/home/app/repo.git checkout -f main`

Could I have done something else wrong to create that issue?

I'm going to try the process again to see if the same thing happens.

**Comment by jacobobryant** [comment]
ah yes, that can cause issues. There's an option in `config.edn` you can uncomment to have it push your local `main` branch to the remote `master` branch, so you'll probably want to do that.

In more recent versions of Biff I've actually stopped using git for deploys due to issues like this, but the tutorial has you use an old version of Biff because I haven't updated it yet. I'm planning to update it soon though, once I finish another Biff release I'm working on, so once that's done deploys should work without any config tweaking.

**Comment by mintymac** [comment]
That makes sense, if there are simple things to do, I'm happy to chip in with docs too

**Comment by jacobobryant** [comment]
As part of the [1.8.0 release](https://github.com/jacobobryant/biff/discussions/186) I've updated the tutorial, so this error should come up much less often, since git will only be used for deploys if `rsync` isn't installed.
